(function(){var aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},n="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},ca=ba(this),p=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&n(c,a,{configurable:!0,writable:!0,value:b})}};
p("Symbol",function(a){if(a)return a;var b=function(f,k){this.ha=f;n(this,"description",{configurable:!0,writable:!0,value:k})};b.prototype.toString=function(){return this.ha};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e});
p("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ca[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&n(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});
var da=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},q=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");},r=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
p("WeakMap",function(a){function b(){}function c(h){var l=typeof h;return"object"===l&&null!==h||"function"===l}function d(h){if(!r(h,f)){var l=new b;n(h,f,{value:l})}}function e(h){var l=Object[h];l&&(Object[h]=function(m){if(m instanceof b)return m;Object.isExtensible(m)&&d(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var h=Object.seal({}),l=Object.seal({}),m=new a([[h,2],[l,3]]);if(2!=m.get(h)||3!=m.get(l))return!1;m.delete(h);m.set(l,4);return!m.has(h)&&4==m.get(l)}catch(G){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var k=0,g=function(h){this.u=(k+=Math.random()+1).toString();if(h){h=q(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}};g.prototype.set=function(h,l){if(!c(h))throw Error("Invalid WeakMap key");d(h);if(!r(h,f))throw Error("WeakMap key fail: "+h);h[f][this.u]=l;return this};g.prototype.get=function(h){return c(h)&&r(h,f)?h[f][this.u]:void 0};g.prototype.has=function(h){return c(h)&&r(h,f)&&r(h[f],this.u)};
g.prototype.delete=function(h){return c(h)&&r(h,f)&&r(h[f],this.u)?delete h[f][this.u]:!1};return g});
p("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var g=Object.seal({x:4}),h=new a(q([[g,"s"]]));if("s"!=h.get(g)||1!=h.size||h.get({x:4})||h.set({x:4},"t")!=h||2!=h.size)return!1;var l=h.entries(),m=l.next();if(m.done||m.value[0]!=g||"s"!=m.value[1])return!1;m=l.next();return m.done||4!=m.value[0].x||"t"!=m.value[1]||!l.next().done?!1:!0}catch(G){return!1}}())return a;var b=new WeakMap,c=function(g){this[0]={};this[1]=
f();this.size=0;if(g){g=q(g);for(var h;!(h=g.next()).done;)h=h.value,this.set(h[0],h[1])}};c.prototype.set=function(g,h){g=0===g?0:g;var l=d(this,g);l.list||(l.list=this[0][l.id]=[]);l.h?l.h.value=h:(l.h={next:this[1],m:this[1].m,head:this[1],key:g,value:h},l.list.push(l.h),this[1].m.next=l.h,this[1].m=l.h,this.size++);return this};c.prototype.delete=function(g){g=d(this,g);return g.h&&g.list?(g.list.splice(g.index,1),g.list.length||delete this[0][g.id],g.h.m.next=g.h.next,g.h.next.m=g.h.m,g.h.head=
null,this.size--,!0):!1};c.prototype.clear=function(){this[0]={};this[1]=this[1].m=f();this.size=0};c.prototype.has=function(g){return!!d(this,g).h};c.prototype.get=function(g){return(g=d(this,g).h)&&g.value};c.prototype.entries=function(){return e(this,function(g){return[g.key,g.value]})};c.prototype.keys=function(){return e(this,function(g){return g.key})};c.prototype.values=function(){return e(this,function(g){return g.value})};c.prototype.forEach=function(g,h){for(var l=this.entries(),m;!(m=l.next()).done;)m=
m.value,g.call(h,m[1],m[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(g,h){var l=h&&typeof h;"object"==l||"function"==l?b.has(h)?l=b.get(h):(l=""+ ++k,b.set(h,l)):l="p_"+h;var m=g[0][l];if(m&&r(g[0],l))for(g=0;g<m.length;g++){var G=m[g];if(h!==h&&G.key!==G.key||h===G.key)return{id:l,list:m,index:g,h:G}}return{id:l,list:m,index:-1,h:void 0}},e=function(g,h){var l=g[1];return da(function(){if(l){for(;l.head!=g[1];)l=l.m;for(;l.next!=l.head;)return l=l.next,{done:!1,value:h(l)};
l=null}return{done:!0,value:void 0}})},f=function(){var g={};return g.m=g.next=g.head=g},k=0;return c});var ea=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};p("Array.prototype.keys",function(a){return a?a:function(){return ea(this,function(b){return b})}});
p("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var k=d[f];if(b.call(c,k,f,d)){b=k;break a}}b=void 0}return b}});p("Array.prototype.entries",function(a){return a?a:function(){return ea(this,function(b,c){return[b,c]})}});
p("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(g){return g};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var k=0;!(f=b.next()).done;)e.push(c.call(d,f.value,k++))}else for(f=b.length,k=0;k<f;k++)e.push(c.call(d,b[k],k));return e}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var t=t||{},u=this||self,v=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},fa=function(a,b,c){return a.call.apply(a.bind,arguments)},ha=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},w=function(a,b,c){w=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?
fa:ha;return w.apply(null,arguments)},x=function(a,b){function c(){}c.prototype=b.prototype;a.U=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.sa=function(d,e,f){for(var k=Array(arguments.length-2),g=2;g<arguments.length;g++)k[g-2]=arguments[g];return b.prototype[e].apply(d,k)}};function y(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,y);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b)}x(y,Error);y.prototype.name="CustomError";function z(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");y.call(this,c+a[d])}x(z,y);z.prototype.name="AssertionError";var A=function(a,b,c){if(!a){var d="Assertion failed";if(b){d+=": "+b;var e=Array.prototype.slice.call(arguments,2)}throw new z(""+d,e||[]);}},ia=function(a,b){throw new z("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var ja=Array.prototype.indexOf?function(a,b){A(null!=a.length);return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};var B=function(){this.O=this.O};B.prototype.O=!1;var C=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.B=!1};C.prototype.stopPropagation=function(){this.B=!0};C.prototype.preventDefault=function(){this.defaultPrevented=!0};var ka=Object.freeze||function(a){return a};var la=function(){if(!u.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{var c=function(){};u.addEventListener("test",c,b);u.removeEventListener("test",c,b)}catch(d){}return a}();function D(){var a=u.navigator;return a&&(a=a.userAgent)?a:""};var E=function(a){E[" "](a);return a};E[" "]=function(){};var ma=-1!=D().indexOf("Gecko")&&!(-1!=D().toLowerCase().indexOf("webkit")&&-1==D().indexOf("Edge"))&&!(-1!=D().indexOf("Trident")||-1!=D().indexOf("MSIE"))&&-1==D().indexOf("Edge"),na=-1!=D().toLowerCase().indexOf("webkit")&&-1==D().indexOf("Edge");var F=function(a,b){C.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.timeStamp=0;this.s=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;
this.currentTarget=b;if(b=a.relatedTarget){if(ma){a:{try{E(b.nodeName);var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.offsetX=na||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=na||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?
a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:oa[a.pointerType]||"";this.state=a.state;this.timeStamp=a.timeStamp;this.s=
a;a.defaultPrevented&&F.U.preventDefault.call(this)}};x(F,C);var oa=ka({2:"touch",3:"pen",4:"mouse"});F.prototype.stopPropagation=function(){F.U.stopPropagation.call(this);this.s.stopPropagation?this.s.stopPropagation():this.s.cancelBubble=!0};F.prototype.preventDefault=function(){F.U.preventDefault.call(this);var a=this.s;a.preventDefault?a.preventDefault():a.returnValue=!1};var H="closure_listenable_"+(1E6*Math.random()|0);var pa=0;var qa=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.G=e;this.key=++pa;this.C=this.D=!1},I=function(a){a.C=!0;a.listener=null;a.proxy=null;a.src=null;a.G=null};function ra(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}var sa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function ta(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<sa.length;f++)c=sa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var J=function(a){this.src=a;this.j={};this.L=0};J.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.j[f];a||(a=this.j[f]=[],this.L++);var k=K(a,b,d,e);-1<k?(b=a[k],c||(b.D=!1)):(b=new qa(b,this.src,f,!!d,e),b.D=c,a.push(b));return b};J.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.j))return!1;var e=this.j[a];b=K(e,b,c,d);return-1<b?(I(e[b]),A(null!=e.length),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.j[a],this.L--),!0):!1};
var L=function(a,b){var c=b.type;if(c in a.j){var d=a.j[c],e=ja(d,b),f;if(f=0<=e)A(null!=d.length),Array.prototype.splice.call(d,e,1);f&&(I(b),0==a.j[c].length&&(delete a.j[c],a.L--))}};J.prototype.R=function(a,b,c,d){a=this.j[a.toString()];var e=-1;a&&(e=K(a,b,c,d));return-1<e?a[e]:null};J.prototype.hasListener=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return ra(this.j,function(f){for(var k=0;k<f.length;++k)if(!(c&&f[k].type!=d||e&&f[k].capture!=b))return!0;return!1})};
var K=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.C&&f.listener==b&&f.capture==!!c&&f.G==d)return e}return-1};var M="closure_lm_"+(1E6*Math.random()|0),ua={},va=0,xa=function(a,b,c,d,e){if(d&&d.once)wa(a,b,c,d,e);else if(Array.isArray(b))for(var f=0;f<b.length;f++)xa(a,b[f],c,d,e);else c=ya(c),a&&a[H]?(d=v(d)?!!d.capture:!!d,za(a),a.l.add(String(b),c,!1,d,e)):Aa(a,b,c,!1,d,e)},Aa=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var k=v(e)?!!e.capture:!!e,g=Ba(a);g||(a[M]=g=new J(a));c=g.add(b,c,d,k,f);if(!c.proxy){d=Ca();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)la||(e=k),void 0===
e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Da(b.toString()),d);else if(a.addListener&&a.removeListener)A("change"===b,"MediaQueryList only has a change event"),a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");va++}},Ca=function(){var a=Ea,b=function(c){return a.call(b.src,b.listener,c)};return b},wa=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)wa(a,b[f],c,d,e);else c=ya(c),a&&a[H]?a.l.add(String(b),
c,!0,v(d)?!!d.capture:!!d,e):Aa(a,b,c,!0,d,e)},Fa=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Fa(a,b[f],c,d,e);else d=v(d)?!!d.capture:!!d,c=ya(c),a&&a[H]?a.l.remove(String(b),c,d,e):a&&(a=Ba(a))&&(b=a.R(b,c,d,e))&&Ga(b)},Ga=function(a){if("number"!==typeof a&&a&&!a.C){var b=a.src;if(b&&b[H])L(b.l,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Da(c),d):b.addListener&&b.removeListener&&b.removeListener(d);
va--;(c=Ba(b))?(L(c,a),0==c.L&&(c.src=null,b[M]=null)):I(a)}}},Da=function(a){return a in ua?ua[a]:ua[a]="on"+a},Ea=function(a,b){if(a.C)a=!0;else{b=new F(b,this);var c=a.listener,d=a.G||a.src;a.D&&Ga(a);a=c.call(d,b)}return a},Ba=function(a){a=a[M];return a instanceof J?a:null},Ha="__closure_events_fn_"+(1E9*Math.random()>>>0),ya=function(a){A(a,"Listener can not be null.");if("function"===typeof a)return a;A(a.handleEvent,"An object listener must have handleEvent method.");a[Ha]||(a[Ha]=function(b){return a.handleEvent(b)});
return a[Ha]};var N=function(){B.call(this);this.l=new J(this);this.ia=this;this.da=null};x(N,B);N.prototype[H]=!0;N.prototype.addEventListener=function(a,b,c,d){xa(this,a,b,c,d)};N.prototype.removeEventListener=function(a,b,c,d){Fa(this,a,b,c,d)};
N.prototype.dispatchEvent=function(a){za(this);var b=this.da;if(b){var c=[];for(var d=1;b;b=b.da)c.push(b),A(1E3>++d,"infinite loop")}b=this.ia;d=a.type||a;if("string"===typeof a)a=new C(a,b);else if(a instanceof C)a.target=a.target||b;else{var e=a;a=new C(d,b);ta(a,e)}e=!0;if(c)for(var f=c.length-1;!a.B&&0<=f;f--){var k=a.currentTarget=c[f];e=O(k,d,!0,a)&&e}a.B||(k=a.currentTarget=b,e=O(k,d,!0,a)&&e,a.B||(e=O(k,d,!1,a)&&e));if(c)for(f=0;!a.B&&f<c.length;f++)k=a.currentTarget=c[f],e=O(k,d,!1,a)&&
e;return e};var O=function(a,b,c,d){b=a.l.j[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var k=b[f];if(k&&!k.C&&k.capture==c){var g=k.listener,h=k.G||k.src;k.D&&L(a.l,k);e=!1!==g.call(h,d)&&e}}return e&&!d.defaultPrevented};N.prototype.R=function(a,b,c,d){return this.l.R(String(a),b,c,d)};N.prototype.hasListener=function(a,b){return this.l.hasListener(void 0!==a?String(a):void 0,b)};var za=function(a){A(a.l,"Event target is not initialized. Did you call the superclass (goog.events.EventTarget) constructor?")};var P=function(a,b){this.name=a;this.value=b};P.prototype.toString=function(){return this.name};var Q=new P("OFF",Infinity),Ia=new P("SEVERE",1E3),Ja=new P("CONFIG",700),Ka=new P("FINE",500),La=function(){this.F=0;this.clear()},Ma;La.prototype.clear=function(){this.W=Array(this.F);this.Y=-1;this.Z=!1};var Na=function(a,b,c){this.reset(a||Q,b,c,void 0,void 0)};Na.prototype.reset=function(){};
var Oa=function(a,b){this.level=null;this.ja=[];this.parent=(void 0===b?null:b)||null;this.children=[];this.ka={S:function(){return a}}},Pa=function(a){if(a.level)return a.level;if(a.parent)return Pa(a.parent);ia("Root logger has no level set.");return Q},Qa=function(a,b){for(;a;)a.ja.forEach(function(c){c(b)}),a=a.parent},Ra=function(){this.entries={};var a=new Oa("");a.level=Ja;this.entries[""]=a},Sa,R=function(a,b){var c=a.entries[b];if(c)return c;c=R(a,b.slice(0,Math.max(b.lastIndexOf("."),0)));
var d=new Oa(b,c);a.entries[b]=d;c.children.push(d);return d},Ta=function(){Sa||(Sa=new Ra);return Sa},Ua=function(a,b,c){var d;if(d=a)if(d=a&&b){d=b.value;var e=a?Pa(R(Ta(),a.S())):Q;d=d>=e.value}if(d){b=b||Q;d=R(Ta(),a.S());"function"===typeof c&&(c=c());Ma||(Ma=new La);e=Ma;a=a.S();if(0<e.F){var f=(e.Y+1)%e.F;e.Y=f;e.Z?(e=e.W[f],e.reset(b,c,a),a=e):(e.Z=f==e.F-1,a=e.W[f]=new Na(b,c,a))}else a=new Na(b,c,a);Qa(d,a)}},Va=function(a,b){a&&Ua(a,Ia,b)},S=function(a,b){a&&Ua(a,Ka,b)};var Wa=function(){};Wa.prototype.X=null;var Xa=function(a){var b;(b=a.X)||(b=a.X={});return b};var Ya,Za=function(){};x(Za,Wa);Ya=new Za;/*

 SPDX-License-Identifier: Apache-2.0
*/
var $a={};var ab=function(a){if($a!==$a)throw Error("Bad secret");this.pa=a};ab.prototype.toString=function(){return this.pa};new ab("about:blank");new ab("about:invalid#zClosurez");var bb=[],cb=function(a){console.warn("A URL with content '"+a+"' was sanitized away.")};-1===bb.indexOf(cb)&&bb.push(cb);var db={},eb=function(){if(db!==db)throw Error("SafeStyle is not meant to be built directly");this.oa=""};eb.prototype.toString=function(){return this.oa.toString()};new eb;var fb={},gb=function(){if(fb!==fb)throw Error("SafeStyleSheet is not meant to be built directly");this.na=""};gb.prototype.toString=function(){return this.na.toString()};new gb;var hb={},ib=function(){var a=u.trustedTypes&&u.trustedTypes.emptyHTML||"";if(hb!==hb)throw Error("SafeHtml is not meant to be built directly");this.ma=a};ib.prototype.toString=function(){return this.ma.toString()};new ib;var jb=function(a,b,c){if("function"===typeof a)c&&(a=w(a,c));else if(a&&"function"==typeof a.handleEvent)a=w(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:u.setTimeout(a,b||0)};var kb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");var T=function(a){N.call(this);this.headers=new Map;this.ga=a||null;this.o=!1;this.M=this.g=null;this.A=this.aa=this.I="";this.v=this.T=this.H=this.P=!1;this.K=0;this.J=null;this.ea="";this.qa=this.fa=!1;this.N=this.V=null};x(T,N);T.prototype.i=R(Ta(),"goog.net.XhrIo").ka;var lb=/^https?$/i,mb=["POST","PUT"];T.prototype.setTrustToken=function(a){this.V=a};T.prototype.setAttributionReporting=function(a){this.N=a};
T.prototype.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.I+"; newUri="+a);b=b?b.toUpperCase():"GET";this.I=a;this.A="";this.aa=b;this.P=!1;this.o=!0;this.g=new XMLHttpRequest;this.M=this.ga?Xa(this.ga):Xa(Ya);this.g.onreadystatechange=w(this.ca,this);this.qa&&"onprogress"in this.g&&(this.g.onprogress=w(function(k){this.ba(k,!0)},this),this.g.upload&&(this.g.upload.onprogress=w(this.ba,this)));try{S(this.i,U(this,"Opening Xhr")),this.T=
!0,this.g.open(b,String(a),!0),this.T=!1}catch(k){S(this.i,U(this,"Error opening Xhr: "+k.message));nb(this,k);return}a=c||"";c=new Map(this.headers);if(d)if(Object.getPrototypeOf(d)===Object.prototype)for(var e in d)c.set(e,d[e]);else if("function"===typeof d.keys&&"function"===typeof d.get){e=q(d.keys());for(var f=e.next();!f.done;f=e.next())f=f.value,c.set(f,d.get(f))}else throw Error("Unknown input type for opt_headers: "+String(d));d=Array.from(c.keys()).find(function(k){return"content-type"==
k.toLowerCase()});e=u.FormData&&a instanceof u.FormData;!(0<=ja(mb,b))||d||e||c.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");b=q(c);for(d=b.next();!d.done;d=b.next())c=q(d.value),d=c.next().value,c=c.next().value,this.g.setRequestHeader(d,c);this.ea&&(this.g.responseType=this.ea);"withCredentials"in this.g&&this.g.withCredentials!==this.fa&&(this.g.withCredentials=this.fa);if("setTrustToken"in this.g&&this.V)try{this.g.setTrustToken(this.V)}catch(k){S(this.i,U(this,"Error SetTrustToken: "+
k.message))}if("setAttributionReporting"in this.g&&this.N)try{this.g.setAttributionReporting(this.N)}catch(k){S(this.i,U(this,"Error SetAttributionReporting: "+k.message))}try{ob(this),0<this.K&&(S(this.i,U(this,"Will abort after "+this.K+"ms if incomplete")),this.J=jb(this.ra,this.K,this)),S(this.i,U(this,"Sending request")),this.H=!0,this.g.send(a),this.H=!1}catch(k){S(this.i,U(this,"Send error: "+k.message)),nb(this,k)}};
T.prototype.ra=function(){"undefined"!=typeof t&&this.g&&(this.A="Timed out after "+this.K+"ms, aborting",S(this.i,U(this,this.A)),this.dispatchEvent("timeout"),this.abort(8))};var nb=function(a,b){a.o=!1;a.g&&(a.v=!0,a.g.abort(),a.v=!1);a.A=b;pb(a);qb(a)},pb=function(a){a.P||(a.P=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))};
T.prototype.abort=function(){this.g&&this.o&&(S(this.i,U(this,"Aborting")),this.o=!1,this.v=!0,this.g.abort(),this.v=!1,this.dispatchEvent("complete"),this.dispatchEvent("abort"),qb(this))};T.prototype.ca=function(){this.O||(this.T||this.H||this.v?rb(this):this.la())};T.prototype.la=function(){rb(this)};
var rb=function(a){if(a.o&&"undefined"!=typeof t)if(a.M[1]&&4==V(a)&&2==W(a))S(a.i,U(a,"Local request error detected and ignored"));else if(a.H&&4==V(a))jb(a.ca,0,a);else if(a.dispatchEvent("readystatechange"),4==V(a)){S(a.i,U(a,"Request complete"));a.o=!1;try{var b=W(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=String(a.I).match(kb)[1]||null;!f&&u.self&&u.self.location&&(f=u.self.location.protocol.slice(0,
-1));e=!lb.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");else{try{var k=2<V(a)?a.g.statusText:""}catch(g){S(a.i,"Can not get status: "+g.message),k=""}a.A=k+" ["+W(a)+"]";pb(a)}}finally{qb(a)}}};T.prototype.ba=function(a,b){A("progress"===a.type,"goog.net.EventType.PROGRESS is of the same type as raw XHR progress.");this.dispatchEvent(sb(a,"progress"));this.dispatchEvent(sb(a,b?"downloadprogress":"uploadprogress"))};
var sb=function(a,b){return{type:b,lengthComputable:a.lengthComputable,loaded:a.loaded,total:a.total}},qb=function(a){if(a.g){ob(a);var b=a.g,c=a.M[0]?function(){}:null;a.g=null;a.M=null;a.dispatchEvent("ready");try{b.onreadystatechange=c}catch(d){Va(a.i,"Problem encountered resetting onreadystatechange: "+d.message)}}},ob=function(a){a.J&&(u.clearTimeout(a.J),a.J=null)};T.prototype.isActive=function(){return!!this.g};
var V=function(a){return a.g?a.g.readyState:0},W=function(a){try{return 2<V(a)?a.g.status:-1}catch(b){return-1}};T.prototype.getResponseHeader=function(a){if(this.g&&4==V(this))return a=this.g.getResponseHeader(a),null===a?void 0:a};T.prototype.getAllResponseHeaders=function(){return this.g&&2<=V(this)?this.g.getAllResponseHeaders()||"":""};var U=function(a,b){return b+" ["+a.aa+" "+a.I+" "+W(a)+"]"};var tb=function(a,b){var c=new botguard.bg(a);setTimeout(function(){c.invoke(function(d){(b||new T).send("/b/csi.do","POST","t="+d)})},5E3)},X=["BLOG_processCsi"],Y=u;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===tb?Y=Y[Z]&&Y[Z]!==Object.prototype[Z]?Y[Z]:Y[Z]={}:Y[Z]=tb;}).call(this);
